project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - busi448.qmd
    - research.qmd


website:
  title: ""
  search: false

  navbar:
    search: false
    left:
      - text: "Home"
        file: index.qmd

      - text: "Research"
        file: research.qmd     

      - text: "BUSI 448"
        file: busi448.qmd       

      - text: "CV" 
        file: KevinCrottyCV.pdf

                            

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



